### PR TITLE
CMake fixes.

### PR DESCRIPTION
**Pull request by isaachier**
Overall CMake fixes with help from @ruslo (see https://github.com/hunter-packages/double-conversion/pull/1).

### CODE REVIEW

**Comment by isaachier** [comment]
I signed it!

**Comment by floitschG** [comment]
Thanks.
I will try later, but will the change in the include directives (from relative include to `<double-conversion`) not make things harder for `scons` or other build systems?

**Comment by isaachier** [comment]
Interesting point. The reverse point was made when submitting this change. Basically, using the local directory as global include path could easily cause collision with existing headers. For example, "utils.h" is ambiguous. Will test scons but understand the concern.

**Comment by floitschG** [comment]
The library was initially developed for V8, and is used in most JavaScript engines now. Afaik they all fetch a copy and use it from a third-party directory.
See Dart here: https://github.com/dart-lang/sdk/tree/master/runtime/third_party/double-conversion
Firefox here: https://dxr.mozilla.org/mozilla-central/source/mfbt/double-conversion/source

That said: I think we can drop `scons` support if that gets annoying. (I would just update the `Makefile` which I use to build and run tests).
Also, these projects can patch the files if necessary. However, it would be great, if the work for them wouldn't be too bad. (It seems like they aren't updating too often anyway).

**Comment by isaachier** [comment]
Actually SCons build worked fine for me.

**Comment by floitschG** [comment]
Thanks.

**Pull request merged**
