### PR TITLE
two little cleanup fixes

### PR DESCRIPTION
**Pull request by aiq**
Hey I discovered two little discrepancies in the code that I changed/fixed.

### CODE REVIEW

**Comment by floitsch** [comment]
Thanks.

**Comment by floitschG** [comment]
Sorry to reopen this after several months...
Could you please sign Google's CLA [0].
I thought that small patches don't need to go through that process, but apparently I was wrong... :(
Thanks.

[0] https://cla.developers.google.com/about/google-individual

**Comment by aiq** [comment]
Signed Google's CLA, I hope everything is now ok.

**Comment by floitschG** [comment]
Just verified. Thanks!

**Pull request merged**
