### PR TITLE
Add fPIC flag on x86_64 if the compiler supports it.

### LINKED ISSUE #34: cmake not building with fPIC
scons adds -fPIC but cmake does not. 

Adding this to double-conversion/src/CMakeLists.txt solved my problem:

```
if (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set_target_properties(double-conversion PROPERTIES COMPILE_FLAGS "-fPIC")
endif()
```

### PR DESCRIPTION
**Pull request by floitschG**
Fixes #34.

### CODE REVIEW

**Comment by chadrik** [comment]
whoops, there's a typo in `CMAKE_SYSTEM_PROCESSOR`!

**Comment by floitsch** [comment]
Weird. I thought I had tested it.
Will fix immediately.

**Comment by chadrik** [comment]
Took me awhile to notice it as well because cmake doesn't error when you reference undefined variables, it just silently treats the value as false.

**Comment by floitschG** [comment]
That explains it.

**Pull request merged**
