### PR TITLE
add support for a new architecture loongarch.

### PR DESCRIPTION
**Pull request by houfangdong**
the loongarch architecture can also support this library, hoping to be integrated into it，the following is my experiment on this machine：

Signed-off-by: houfangdong@loongson.cn

### CODE REVIEW

**Review by floitsch — APPROVED** [review]
LGTM!

thanks.

**Comment by floitsch** [comment]
Before committing.
Do the tests run successfully?

**Comment by houfangdong** [comment]
This is the process of make test. 

What else do you need to do?
In addition, my google (CLA) has already been signed, and I don’t know why it has been prompted to fail.
Please help me, thanks

**Comment by houfangdong** [comment]
@googlebot I fixed it.

**Comment by floitsch** [comment]
Don't worry about the CLA. I can override that one.
Could you maybe add a small entry to the Changelog? Once that's done I would happily commit it.
thanks.

**Comment by houfangdong** [comment]
@floitsch，thanks for your suggestion, the changlog has been modified.

**Comment by floitsch** [comment]
Thanks!

**Pull request merged**
