### PR TITLE
Add support for the RISC-V ISA

### PR DESCRIPTION
**Pull request by sorear**
Tested under the qemu emulator, both in isolation and as part of SpiderMonkey.

### CODE REVIEW

**Comment by sorear** [comment]
Getting an error from the CLA page: "You must be an owner of the contributors group in order to submit this CLA."  Any ideas?

**Comment by floitsch** [comment]
Thanks for the pull request.

I will try to find out what could be the reason for that error message.
Given the size of the change I'm pretty sure I could do the change for you, but I would prefer to just merge the request.

**Comment by sorear** [comment]
Relevant detail: I have a work and personal google account, the personal account is ordinal `1`, and the CLA page doesn't have an account menu so I manually added `?authuser=1` to the URL, which caused it to get the correct email.

I can try logging out of everything and redoing it later so that the account I want becomes `0`, I suspect that will make the CLA page happier.

**Comment by floitsch** [comment]
That could be it. Maybe just try to sign it in an incognito window. That would avoid logging out of your account.

**Comment by sorear** [comment]
@floitsch That did the trick

(does googlebot look for any ticket activity, like this, or is there more to it)

**Comment by floitsch** [comment]
That should do it.
Thanks!

**Pull request merged**
