### PR TITLE
Fix naming.

### PR DESCRIPTION
**Pull request by ColinH**
The generally agreed term is "case insensitivity" rather than "case insensibility".

### CODE REVIEW

**Comment by floitsch** [comment]
Hmm.
That would be a breaking change. I guess, for compatibility, we should leave the old constant around (and add a comment that it is deprecated in favor of the correctly named constant).

**Comment by floitsch** [comment]
As discussed in the other PR:
update the Changelog.

and feel free to add yourself to the AUTHORS file.

**Comment by ColinH** [comment]
Should be ready now.

**Comment by floitsch** [comment]
Thanks!

**Pull request merged**
