### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by luzpaz** [comment]
Typos found downstream: https://github.com/unicode-org/icu/pull/1764#issuecomment-880350002

**Comment by luzpaz** [comment]
I'd like to sign the CLA, why is it asking me to log in to google. Most CLAs don't.

**Review by floitsch — APPROVED** [review]
LGTM.

**Comment by floitsch** [comment]
The CLA is standard Google. I will override it in this case.
Thanks for the patch!

**Pull request merged**
