### PR TITLE
fixed inconsistent include paths

### PR DESCRIPTION
**Pull request by mihaipopescu**
fixed inconsistent include paths
also, fixed compile error when library is included with the root to double-conversion source folder

### CODE REVIEW

**Comment by ilelann** [comment]
It seems my pull request https://github.com/google/double-conversion/pull/19 is another way to fix this ? Am I correct ?

**Comment by mihaipopescu** [comment]
@ilelann You are right but the fix needs to be independent of the build system.

**Comment by mihaipopescu** [comment]
I have asked our legal department and they've instructed me to sign it on my behalf.

It's signed. :white_check_mark:

**Comment by ilelann** [comment]
@mihaipopescu  I guess it is a matter of taste but I usually don't place public headers beside cpp files, which include those headers the same way a thirdparty would.
So I don't see anything wrong with those ```#include "double-conversion/foo.h"```.
Anyway, I only wanted to warn the maintainer that our two requests address a similar issue, although my focus is more on using the library than on building it.

**Comment by mihaipopescu** [comment]
This PR fixes include folder path inconsistencies across all _cpp_ files as some include header files with `double-conversion/` folder and others without while all being organized in the same folder.

If you want another organization (i.e. *include* and *src* folders) I guess that would be something else.

**Comment by floitschG** [comment]
I guess it makes sense to just include them relatively.
There is an argument for moving the headers into a separate directory, but I don't think it's necessary to do it now.

**Pull request merged**
