### PR TITLE
Consistent macro prefix.

### PR DESCRIPTION
**Pull request by ColinH**
Small change to use a consistent macro prefix for _all_ macros.

PS: Among other possible improvements, some macros would be made redundant by updating to C++11 (or later), but I'm guessing that's not on the table for this project.

### CODE REVIEW

**Comment by floitsch** [comment]
LGTM.
Could you please change the Changelog file with a small entry.
Thanks!

**Comment by floitsch** [comment]
I don't think there is a need to switch to C++11. Especially, since the current macros work.

**Comment by ColinH** [comment]
Ok for changelog, give me a minute...

As for C++11, of course it's not needed since the library works fine without it, I just couldn't help but notice a few places that would benefit from having C++11 or 17 available :-)

**Comment by floitsch** [comment]
Yeah. The library is getting old. Now, some code would look differently...

Since there are several changes, might as well wait with the changelog until all of them are committed.

**Comment by floitsch** [comment]
There is a conflict now (because of me merging the min/max change.
Otherwise LGTM.

Fine with the Changelog change.
I would suggest updating the Changelog in the PR for the API change as well (deprecating the misspelled constant).
If you have other PRs coming, you can also create a final PR for the changelog to avoid potential conflicts.

**Comment by ColinH** [comment]
OK, forgot to check for for conflicts first, sorry. I'll first fix the conflict, and then update the Changelog in the naming PR (and re-introduce the old public names for compatibility).

**Comment by ColinH** [comment]
I don't have any PRs right now, though I was wondering about some functions that took a mandatory "out" (or "in-out") argument by pointer, rather than by reference, and was wondering whether that was an artefact of old C-style coding, or a deliberate choice (so that the caller must pass `&variable`, thereby signalling that something more than passing a value to the caller is happening).

**Comment by floitsch** [comment]
Exactly. It's one of my conventions to make it easier to see that an argument is used as out-parameter.

**Comment by ColinH** [comment]
For the record, if you ever do update to a newer C++ standard:

- Use `std::array` (and remove `DOUBLE_CONVERSION_ARRAY_SIZE`), requires C++11.
- Use `Type() = delete` etc. (and remove `DOUBLE_CONVERSION_DISALLOW...` etc), requires C++11.
- Use `[[maybe_unused]]` (and remove `DOUBLE_CONVERSION_UNUSED`), requires C++17.

Some places might also benefit from `[[nodiscard]]` and `static_assert`, and there's bound to be more if one digs deeper, there usually is :-)

**Comment by floitsch** [comment]
:)
Thanks.

**Comment by ericLemanissier** [comment]
@floitsch @ColinH Do I understand correctly that this change is a source incompatibility introduced in a patch version ? isn't there a way to get the old macros with 3.1.6 (for example `UINT64_2PART_C`) ? Or are these macro implementation details which should not be used by consumers ?

**Comment by floitsch** [comment]
Hmm. Good point. I didn't realize this patch would break users.

I don't think these macros should have been exposed before.

I don't see a good way out of this, except for increasing the major version number.
I could release another 3.X version that goes back to where we were before and create a new 4.X version with the changed macro names. Wdyt?

**Comment by ericLemanissier** [comment]
Usually such transitions are made with an intermediate step where consumer can choose the syntax. I think the best solution is to define the old non prefixed macros if the consumer chooses to opt in via `#define DOUBLE_CONVERSION_NON_PREFIXED_MACRO`, at least for the 3.1.X series (or better, for the whole 3.X.Y series)

**Comment by floitsch** [comment]
Created a PR: https://github.com/google/double-conversion/pull/169

**Pull request merged**
